### ISSUE TITLE
CSV for FileDataSourceStrategy might not be the best....

### ISSUE THREAD

**Issue by Mcdostone** [Chocorean/authmod-core#1]
## Configuration
- `identifierRequired` is set to `true`
- `enableRegister` is set to `true`
- `dataSource` is set to `FILE`

## Issue  
What if I register and execute the command :
`/register "my-identifier," "<password" "<password>"`
> (notice the comma for the identifier)
 
```csv
# Identifier, username, hashed password, uuid, is banned ?
my_identifier,,Dev,$2a$10$6lviJDxLWLSnJna8DONEdeGS/bpnFYU/TZruHRwh8lT3qVTmq9XvG,4ea8a9c1-a267-3439-bef2-ade9cdd1a026,false
```

Indeed, this is a **CSV injection**.

**Comment by Chocorean** [comment]
https://github.com/Chocorean/authmod-core/blob/b4485b2592e941e5c290e341ac2cbce6a57211d4/src/main/java/io/chocorean/authmod/core/datasource/FileDataSourceStrategy.java#L81

[We can surround each field with double quotes to avoid this kind of issues](https://en.wikipedia.org/wiki/Comma-separated_values#General_functionality) as a quick fix

**Comment by Chocorean** [comment]
Why don't we use the same process than for tests? A database file looks great
