### ISSUE TITLE
 issues with same lower/uppercased player names

### ISSUE THREAD

**Issue by Chocorean** [Chocorean/authmod-core#2]
https://github.com/Chocorean/authmod/issues/37

**Comment by Chocorean** [comment]
@Mcdostone I'm not sure how to tackle this for the database strategy. Do yo think [this](https://stackoverflow.com/questions/9970313/mysql-lowercase-to-compare-data/28966770) is our best choice or do you know something else?

**Comment by Mcdostone** [comment]
the issue should be fixed, just need to do some testing
